export const ActionTypes = {
    FETCH_IMAGES_REQUEST: "FETCH_IMAGES_REQUEST",
    FETCH_IMAGES_SUCCESS: "FETCH_IMAGES_SUCCESS",
    FETCH_IMAGES_FAIL: "FETCH_IMAGES_REQUESTED",
    CHANGE_IMAGE_ACTIVE_PAGE: "CHANGE_IMAGE_ACTIVE_PAGE",
    RESET_IMAGE_ACTIVE_PAGE: "RESET_IMAGE_ACTIVE_PAGE",
    FETCH_TOTAL_PAGES: "FETCH_TOTAL_PAGES",
}